Check for SQLite file

diff --git a/.github/workflows/jekyll.yml b/.github/workflows/jekyll.yml
--- a/.github/workflows/jekyll.yml
+++ b/.github/workflows/jekyll.yml
@@ -64,6 +64,8 @@ jobs:
         env:
           ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
         run: python ./scripts/build-site.py
+      - name: Verify SQLite file exists
+        run: ls -lh scripts/ test -f scripts/http_cache.sqlite && echo "File exists" || echo "File missing"
       - name: Save HTTP cache
         if: always()
         uses: actions/cache/save@v4
